// config.js — globals, no modules
const CFG={
  APP_NAME:"Ethnographer",STATE_KEY:"ethnographer_v5_state",AMP_MAX:5,BASE_FLOOR:0.02,
  DEFAULT_SETTINGS:{spillover:0.25},
  DEFAULT_TRAITS:[
    {category:"Hair & Skin",key:"skin_colour",name:"Skin Colour",
     colors:["#f2e9d8","#e3caa6","#c59a6a","#8c5a3c","#3b2a22"],
     bins:["Very light","Light","Medium","Dark","Very dark"]},
	 
    {category:"Hair & Skin",key:"hair_colour",name:"Hair Colour",
     colors:["#f3e5ab","#b45309","#6b4f2a","#111827"],
     bins:["Blonde","Red","Brown","Black"]},
	 
    {category:"Hair & Skin",key:"hair_texture",name:"Hair Texture",
     colors:["#7f1d1d","#991b1b","#facc15","#16a34a","#15803d","#d97706","#92400e"],
     bins:["Coarse straight","Fine straight","Wavy","Curly","Tight curly","Kinky","Peppercorn"]},
	 
    {category:"Hair & Skin",key:"body_hair",name:"Body Hair",
     colors:["#93c5fd","#60a5fa","#3b82f6","#2563eb","#1d4ed8"],
     bins:["Hypotrichic","Oligotrichic","Mesotrichic","Hirsute","Hyperhirsute"]},
	 
    {category:"Body",key:"height",name:"Height",
     colors:["#a7f3d0","#6ee7b7","#34d399","#10b981","#059669"],
     bins:["Hypermicrosomic","Microsomic","Mesosomic","Macrosomic","Hypermacrosomic"]},
	 
    {category:"Body",key:"trunk_length",name:"Trunk / Leg Ratio",
     colors:["#ddd6fe","#c4b5fd","#a78bfa","#8b5cf6","#7c3aed"],
     bins:["Hypermacroskelic", "Macroskelic", "Mesoskelic", "Brachyskelic", "Hyperbrachyskelic"]},
	 
    {category:"Body",key:"body_type",name:"Body Type",
     colors:["#fecaca","#fda4af","#fb7185","#f43f5e","#e11d48"],
     bins:["Hyperectomorph","Ectomorph","Mesomorph","Endomorph","Hyperendomorph"]},
	 
    {category:"Body",key:"steatopygia",name:"Steatopygia",
     colors:["#e5e7eb","#d1d5db","#9ca3af","#6b7280","#374151"],
     bins:["None","Mild","Moderate","Pronounced","Steatopygia"]},
	 
    {category:"Head & Skull",key:"cephalic_index",name:"Cephalic Index",
     colors:["#bae6fd","#7dd3fc","#38bdf8","#0ea5e9","#0284c7"],
     bins:["hyperdolichocephalic","Dolichocephalic","Mesocephalic","Brachycephalic","Hyperbrachycephalic"]},
	 
    {category:"Head & Skull",key:"head_height",name:"Head Height",
     colors:["#fde68a","#fcd34d","#f59e0b"],
	 bins:["Chamaecranic","Orthocranic","Hypsicranic"]},
    
	{category:"Head & Skull",key:"head_size",name:"Head Size",
     colors:["#bbf7d0","#86efac","#22c55e"],
	 bins:["Microcephalic","Mesocephalic","Macrocephalic"]},
    
	{category:"Facial",key:"nose_breadth",name:"Nose Breadth",
     colors:["#e9d5ff","#d8b4fe","#c084fc","#a855f7"],
     bins:["Hyperleptorrhine","Leptorrhine","Platyrrhine","Hyperplatyrrhine"]},
    
	{category:"Facial",key:"face_breadth",name:"Face Breadth",
     colors:["#cffafe","#a5f3fc","#67e8f9","#22d3ee","#06b6d4"],
     bins:["Hyperleptoprosop","Leptoprosop","Mesoprosop","Euryprosop","Hypereuryprosop"]},
    
	{category:"Facial",key:"prognathism",name:"Prognathism",
     colors:["#e5e7eb","#cbd5e1","#94a3b8","#64748b"],
     bins:["Hyperorthognathic","Orthognathic","Prognathic","Hyperprognathic"]},
    
	{category:"Facial",key:"eye_folds",name:"Epicanthal Folds",
     colors:["#fef3c7","#fde68a","#fcd34d","#f59e0b"],
     bins:["Anepicanthic","Hypoepicanthic","Mesoepicanthic","Epicanthic"]},
    
	{category:"Facial",key:"male_neoteny",name:"Male Neoteny",
     colors:["#cbd5e1","#93c5fd","#60a5fa","#3b82f6"],
     bins:["Gerontomorphic","Mesomorphic","Paedomorphic","Hyperpaedomorphic"]},
    
	{category:"Facial",key:"female_neoteny",name:"Female Neoteny",
     colors:["#fce7f3","#fbcfe8","#f9a8d4","#ec4899"],
     bins:["Gerontomorphic","Mesomorphic","Paedomorphic","Hyperpaedomorphic"]},
    
	{category:"Metabolism",key:"lactose_tolerance",name:"Lactose Tolerance",
     colors:["#ef4444","#fb923c","#fcd34d","#6ee7b7","#d1fae5"],
     bins:["Alactasic","Hypolactasic","Mesolactasic","Lactasic","Hyperlactasic"]},
    
	{category:"Dimorphism",key:"height_dimorphism",name:"Height Dimorphism",
     colors:["#E7D6E6","#9D87D2","#7E6BA7","#4D3B7D"],
     bins:["Monomorphic","Sub-dimorphic","Mesodimorphic","Dimorphic"]},
    
	{category:"Dimorphism",key:"muscle_dimorphism",name:"Muscle Dimorphism",
     colors:["#ECD6CE","#EA9E83","#C57072","#89464C"],
     bins:["Monomorphic","Sub-dimorphic","Mesodimorphic","Dimorphic"]},
  ],
  PRESET_GROUPS:[
    {name:"Bantuid",
     description:"Broad phenotypic cluster of Sub-Saharan savannah and equatorial belt populations, associated with Niger-Congo language groups and the Bantu dispersal (~3000 BCE–1000 CE). Very dark skin adapted to tropical UV-B. Extremely tight coiled hair minimising solar heat absorption. Sparse body hair maximising sweat-cooling. Wide platyrrhine noses adapted to warm humid air. Dolichocephalic skull, lean limby frame (heat-dissipation). Core Bantuid steatopygia is minimal — pronounced gluteofemoral deposition is characteristic of Khoikhoi/San-adjacent clusters. Lactase persistence low except cattle-herding Nilotic subgroups. Pre-1500 CE distribution.",
     traits:{
      skin_colour:      {binModes:[0,0,1,2,2],peaks:[{mu:3.75,sigma:0.6, amp:3.0}]},
      hair_colour:      {binModes:[0,0,1,2],  peaks:[{mu:3.0, sigma:0.25,amp:4.0}]},
      hair_texture:     {binModes:[0,0,0,1,2,2,2],peaks:[{mu:5.4,sigma:0.85,amp:2.8}]},
      body_hair:        {binModes:[2,2,1,0,0],peaks:[{mu:0.35,sigma:0.5, amp:3.5}]},
      height:           {binModes:[1,2,2,2,1],peaks:[{mu:2.4, sigma:1.0, amp:1.8}]},
      trunk_length:     {binModes:[1,2,2,1,0],peaks:[{mu:1.7, sigma:0.75,amp:2.0}]},
      body_type:        {binModes:[1,2,2,1,0],peaks:[{mu:1.4, sigma:0.75,amp:2.2}]},
      steatopygia:      {binModes:[2,2,1,0,0],peaks:[{mu:0.4, sigma:0.65,amp:3.0}]},
      cephalic_index:   {binModes:[1,2,2,1,0],peaks:[{mu:1.3, sigma:0.75,amp:2.2}]},
      head_height:      {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.55,amp:2.0}]},
      head_size:        {binModes:[1,2,1],    peaks:[{mu:1.1, sigma:0.55,amp:2.0}]},
      nose_breadth:     {binModes:[0,1,2,2],  peaks:[{mu:2.6, sigma:0.7, amp:2.8}]},
      face_breadth:     {binModes:[0,1,2,2,1],peaks:[{mu:2.6, sigma:0.8, amp:2.0}]},
      prognathism:      {binModes:[0,1,2,2],  peaks:[{mu:2.1, sigma:0.75,amp:2.5}]},
      eye_folds:        {binModes:[2,1,0,0],  peaks:[{mu:0.05,sigma:0.3, amp:4.5}]},
      male_neoteny:     {binModes:[2,2,1,0],  peaks:[{mu:0.55,sigma:0.65,amp:2.2}]},
      female_neoteny:   {binModes:[1,2,2,1],  peaks:[{mu:1.1, sigma:0.75,amp:1.8}]},
      lactose_tolerance:{binModes:[2,2,1,1,0],peaks:[{mu:0.6, sigma:0.7, amp:2.8}]},
      height_dimorphism:{binModes:[1,2,2,0],  peaks:[{mu:1.2, sigma:0.6, amp:2.5}]},
      muscle_dimorphism:{binModes:[0,2,2,1],  peaks:[{mu:1.5, sigma:0.65,amp:2.5}]},
    }},
    {name:"Nordid",
     description:"Phenotypic cluster of NW European populations — Scandinavia, British Isles, NW Germany, Low Countries. Post-Ice-Age re-colonisation by WHG and Corded Ware / Bell Beaker steppe ancestry. Very depigmented skin and hair (low UV-B → vitamin D selection). Dolichocephalic, high vault (hypsicephalic), tall lean frame, narrow leptorrhine nose, orthognathous jaw. Moderate-high body hair. Lactase persistence highest globally (~90–95%) — intensive northern cattle-pastoralist selection. Essentially zero steatopygia. Pre-1500 CE.",
     traits:{
      skin_colour:      {binModes:[2,2,1,0,0],peaks:[{mu:0.35,sigma:0.5, amp:3.5}]},
      hair_colour:      {binModes:[2,2,2,1],  peaks:[{mu:0.55,sigma:0.8, amp:2.8}]},
      hair_texture:     {binModes:[1,2,2,1,0,0,0],peaks:[{mu:1.9,sigma:0.8,amp:2.5}]},
      body_hair:        {binModes:[0,1,2,2,1],peaks:[{mu:2.8, sigma:0.7, amp:2.5}]},
      height:           {binModes:[0,1,1,2,2],peaks:[{mu:3.5, sigma:0.65,amp:3.2}]},
      trunk_length:     {binModes:[1,1,2,2,1],peaks:[{mu:2.5, sigma:0.7, amp:2.0}]},
      body_type:        {binModes:[1,2,2,1,0],peaks:[{mu:1.5, sigma:0.75,amp:2.2}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[2,2,1,0,0],peaks:[{mu:0.85,sigma:0.6, amp:3.0}]},
      head_height:      {binModes:[0,1,2],    peaks:[{mu:1.95,sigma:0.4, amp:3.5}]},
      head_size:        {binModes:[1,2,1],    peaks:[{mu:1.05,sigma:0.5, amp:2.5}]},
      nose_breadth:     {binModes:[2,2,1,0],  peaks:[{mu:0.35,sigma:0.5, amp:3.5}]},
      face_breadth:     {binModes:[1,2,2,1,0],peaks:[{mu:1.4, sigma:0.75,amp:2.2}]},
      prognathism:      {binModes:[2,2,1,0],  peaks:[{mu:0.3, sigma:0.45,amp:3.8}]},
      eye_folds:        {binModes:[2,1,0,0],  peaks:[{mu:0.03,sigma:0.28,amp:5.0}]},
      male_neoteny:     {binModes:[1,2,2,1],  peaks:[{mu:1.2, sigma:0.75,amp:2.0}]},
      female_neoteny:   {binModes:[0,1,2,2],  peaks:[{mu:2.2, sigma:0.7, amp:2.2}]},
      lactose_tolerance:{binModes:[0,0,1,2,2],peaks:[{mu:4.0, sigma:0.5, amp:4.0}]},
      height_dimorphism:{binModes:[1,2,2,1],  peaks:[{mu:1.5, sigma:0.65,amp:2.5}]},
      muscle_dimorphism:{binModes:[0,2,2,1],  peaks:[{mu:1.6, sigma:0.65,amp:2.5}]},
    }},
    {name:"Mediterranid",
     description:"Gracile long-headed phenotypic cluster of Mediterranean basin populations — Iberia, Italy, Greece, Anatolia, Levant, Maghreb coast. Associated with Neolithic EEF (Early European Farmer) ancestry from Anatolia. Olive-toned lightly pigmented skin, dark wavy-to-curly hair, notably high body hair density (androgen expression), narrow leptorrhine nose, dolichocephalic skull, small lean frame, orthognathous jaw. Lactase persistence moderate. Sub-variants: Gracile Med (small, narrow), Atlanto-Med (taller, broader), Pontid (eastern, steppe-adjacent). Pre-1500 CE.",
     traits:{
      skin_colour:      {binModes:[1,2,2,1,0],peaks:[{mu:1.7, sigma:0.7, amp:2.5}]},
      hair_colour:      {binModes:[1,0,2,2],  peaks:[{mu:2.5, sigma:0.7, amp:2.8}]},
      hair_texture:     {binModes:[0,1,2,2,1,0,0],peaks:[{mu:2.9,sigma:0.8,amp:2.2}]},
      body_hair:        {binModes:[0,0,1,2,2],peaks:[{mu:3.5, sigma:0.6, amp:3.0}]},
      height:           {binModes:[1,2,2,1,0],peaks:[{mu:1.8, sigma:0.75,amp:2.2}]},
      trunk_length:     {binModes:[1,2,2,1,0],peaks:[{mu:2.0, sigma:0.7, amp:2.0}]},
      body_type:        {binModes:[1,2,2,1,0],peaks:[{mu:1.3, sigma:0.7, amp:2.5}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[1,2,2,1,0],peaks:[{mu:1.3, sigma:0.75,amp:2.2}]},
      head_height:      {binModes:[1,2,1],    peaks:[{mu:1.05,sigma:0.5, amp:2.2}]},
      head_size:        {binModes:[2,2,1],    peaks:[{mu:0.75,sigma:0.5, amp:2.5}]},
      nose_breadth:     {binModes:[2,2,1,0],  peaks:[{mu:0.75,sigma:0.6, amp:2.8}]},
      face_breadth:     {binModes:[1,2,2,1,0],peaks:[{mu:1.5, sigma:0.75,amp:2.2}]},
      prognathism:      {binModes:[1,2,2,0],  peaks:[{mu:0.85,sigma:0.6, amp:2.5}]},
      eye_folds:        {binModes:[2,1,0,0],  peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      male_neoteny:     {binModes:[1,2,2,1],  peaks:[{mu:1.2, sigma:0.75,amp:1.8}]},
      female_neoteny:   {binModes:[0,1,2,2],  peaks:[{mu:1.9, sigma:0.75,amp:2.0}]},
      lactose_tolerance:{binModes:[1,1,2,2,1],peaks:[{mu:2.5, sigma:0.9, amp:1.8}]},
      height_dimorphism:{binModes:[1,2,1,0],  peaks:[{mu:1.2, sigma:0.6, amp:2.8}]},
      muscle_dimorphism:{binModes:[0,2,2,1],  peaks:[{mu:1.5, sigma:0.65,amp:2.5}]},
    }},
    {name:"Tungid",
     description:"Phenotypic cluster of Central and Northeast Asian populations — Mongolian steppe, Siberian taiga/tundra, Gobi. Associated with East Asian / ANE ancestry. Yellowish-olive skin, black coarse straight hair (EDAR 370A derived), extremely sparse body hair (EDAR pleiotropic), very broad flat face, strong Mongolian fold (cold/glare adaptation), brachycephalic skull, stocky robust frame with short limbs (Bergmann/Allen cold-climate body plan), near-zero lactase persistence. Gobid sub-variant: most extreme brachycephaly; Baykal sub-variant: somewhat longer-headed. Pre-1500 CE.",
     traits:{
      skin_colour:      {binModes:[1,2,2,1,0],peaks:[{mu:1.8, sigma:0.65,amp:2.5}]},
      hair_colour:      {binModes:[0,0,1,2],  peaks:[{mu:3.0, sigma:0.22,amp:5.0}]},
      hair_texture:     {binModes:[2,1,0,0,0,0,0],peaks:[{mu:0.18,sigma:0.42,amp:4.5}]},
      body_hair:        {binModes:[2,2,1,0,0],peaks:[{mu:0.3, sigma:0.48,amp:4.0}]},
      height:           {binModes:[1,2,2,1,0],peaks:[{mu:1.6, sigma:0.72,amp:2.5}]},
      trunk_length:     {binModes:[0,1,1,2,2],peaks:[{mu:3.4, sigma:0.65,amp:2.8}]},
      body_type:        {binModes:[0,1,1,2,2],peaks:[{mu:3.3, sigma:0.7, amp:2.8}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[0,0,1,2,2],peaks:[{mu:3.6, sigma:0.6, amp:3.2}]},
      head_height:      {binModes:[2,1,0],    peaks:[{mu:0.15,sigma:0.38,amp:4.5}]},
      head_size:        {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.5, amp:2.2}]},
      nose_breadth:     {binModes:[1,2,2,1],  peaks:[{mu:1.5, sigma:0.7, amp:2.2}]},
      face_breadth:     {binModes:[0,0,1,2,2],peaks:[{mu:3.7, sigma:0.6, amp:3.2}]},
      prognathism:      {binModes:[2,2,1,0],  peaks:[{mu:0.25,sigma:0.45,amp:4.0}]},
      eye_folds:        {binModes:[0,1,2,2],  peaks:[{mu:2.85,sigma:0.55,amp:3.5}]},
      male_neoteny:     {binModes:[0,1,2,2],  peaks:[{mu:2.55,sigma:0.65,amp:2.8}]},
      female_neoteny:   {binModes:[0,0,1,2],  peaks:[{mu:2.8, sigma:0.55,amp:3.2}]},
      lactose_tolerance:{binModes:[2,2,1,0,0],peaks:[{mu:0.3, sigma:0.5, amp:4.0}]},
      height_dimorphism:{binModes:[1,2,1,0],  peaks:[{mu:1.1, sigma:0.6, amp:2.8}]},
      muscle_dimorphism:{binModes:[1,2,2,0],  peaks:[{mu:1.4, sigma:0.65,amp:2.5}]},
    }},
    {name:"Australid",
     description:"Phenotypic cluster of pre-1788 Aboriginal Australian populations. One of the earliest Out-of-Africa dispersals (~65–50 kya), diverging before the European/East Asian split. Distinctive archaic morphology: heavy supraorbital torus, pronounced alveolar prognathism, dolichocephalic skull, very wide platyrrhine nose, lean long-limbed physique, very dark skin. Hair wavy-to-curly — distinct from Bantuid tight kinky/peppercorn. High body hair density (unusual for tropical populations). Near-zero lactase persistence — no dairying tradition pre-contact. Traits reflect ~50 000 years of in-situ evolution on the Australian continent.",
     traits:{
      skin_colour:      {binModes:[0,0,1,2,2],peaks:[{mu:3.6, sigma:0.65,amp:3.0}]},
      hair_colour:      {binModes:[0,0,1,2],  peaks:[{mu:2.9, sigma:0.45,amp:3.2}]},
      hair_texture:     {binModes:[0,0,2,2,2,1,0],peaks:[{mu:3.1,sigma:0.85,amp:2.5}]},
      body_hair:        {binModes:[0,1,2,2,1],peaks:[{mu:3.1, sigma:0.7, amp:2.8}]},
      height:           {binModes:[1,1,2,2,1],peaks:[{mu:2.7, sigma:0.8, amp:2.2}]},
      trunk_length:     {binModes:[1,2,2,1,0],peaks:[{mu:2.0, sigma:0.7, amp:2.0}]},
      body_type:        {binModes:[1,2,2,1,0],peaks:[{mu:1.55,sigma:0.75,amp:2.2}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[1,2,2,1,0],peaks:[{mu:1.4, sigma:0.8, amp:2.2}]},
      head_height:      {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.55,amp:2.0}]},
      head_size:        {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.55,amp:2.0}]},
      nose_breadth:     {binModes:[0,0,1,2],  peaks:[{mu:3.05,sigma:0.45,amp:4.0}]},
      face_breadth:     {binModes:[0,1,2,2,1],peaks:[{mu:2.6, sigma:0.8, amp:2.2}]},
      prognathism:      {binModes:[0,1,2,2],  peaks:[{mu:2.25,sigma:0.7, amp:2.8}]},
      eye_folds:        {binModes:[2,1,0,0],  peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      male_neoteny:     {binModes:[2,2,1,0],  peaks:[{mu:0.35,sigma:0.5, amp:3.5}]},
      female_neoteny:   {binModes:[2,2,1,0],  peaks:[{mu:0.75,sigma:0.6, amp:2.8}]},
      lactose_tolerance:{binModes:[2,2,1,0,0],peaks:[{mu:0.2, sigma:0.45,amp:4.5}]},
      height_dimorphism:{binModes:[1,2,2,0],  peaks:[{mu:1.3, sigma:0.65,amp:2.5}]},
      muscle_dimorphism:{binModes:[1,2,2,0],  peaks:[{mu:1.35,sigma:0.65,amp:2.5}]},
    }},
    {name:"Patagonid",
     description:"Phenotypic cluster of pre-1520 CE Patagonian and Pampas populations — Tehuelche (Aónikenk), Mapuche-adjacent groups. Among the most extreme body-size phenotypes documented: Tehuelche males commonly 180–190 cm (Bergmann cold-climate gigantism + high-protein guanaco/rhea diet). Large brachycephalic-to-mesocephalic skull, broad slightly-flattened face, narrow-to-medium prominent nose. Coarse straight black hair, olive-brown skin, moderate body hair. Partial epicanthal fold reflecting Beringian East Asian ancestry. Absolutely zero lactase persistence — no dairy tradition in pre-contact South America.",
     traits:{
      skin_colour:      {binModes:[0,1,2,2,1],peaks:[{mu:2.3, sigma:0.75,amp:2.5}]},
      hair_colour:      {binModes:[0,0,1,2],  peaks:[{mu:3.0, sigma:0.28,amp:5.0}]},
      hair_texture:     {binModes:[2,1,0,0,0,0,0],peaks:[{mu:0.2,sigma:0.45,amp:4.5}]},
      body_hair:        {binModes:[1,2,2,1,0],peaks:[{mu:1.8, sigma:0.75,amp:2.2}]},
      height:           {binModes:[0,0,1,2,2],peaks:[{mu:3.9, sigma:0.6, amp:3.5}]},
      trunk_length:     {binModes:[0,1,1,2,2],peaks:[{mu:3.5, sigma:0.65,amp:2.8}]},
      body_type:        {binModes:[0,0,1,2,2],peaks:[{mu:3.9, sigma:0.6, amp:3.5}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[0,1,2,2,1],peaks:[{mu:2.8, sigma:0.8, amp:2.5}]},
      head_height:      {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.55,amp:2.2}]},
      head_size:        {binModes:[0,1,2],    peaks:[{mu:2.0, sigma:0.45,amp:3.5}]},
      nose_breadth:     {binModes:[1,2,2,1],  peaks:[{mu:1.3, sigma:0.7, amp:2.5}]},
      face_breadth:     {binModes:[0,0,1,2,2],peaks:[{mu:3.3, sigma:0.7, amp:2.8}]},
      prognathism:      {binModes:[2,2,1,0],  peaks:[{mu:0.5, sigma:0.5, amp:3.5}]},
      eye_folds:        {binModes:[1,2,2,1],  peaks:[{mu:1.3, sigma:0.65,amp:2.5}]},
      male_neoteny:     {binModes:[2,2,1,0],  peaks:[{mu:0.55,sigma:0.6, amp:3.0}]},
      female_neoteny:   {binModes:[1,2,2,1],  peaks:[{mu:1.2, sigma:0.7, amp:2.0}]},
      lactose_tolerance:{binModes:[2,2,1,0,0],peaks:[{mu:0.15,sigma:0.42,amp:5.0}]},
      height_dimorphism:{binModes:[0,1,2,2],  peaks:[{mu:2.4, sigma:0.7, amp:2.8}]},
      muscle_dimorphism:{binModes:[0,0,2,2],  peaks:[{mu:2.6, sigma:0.65,amp:3.0}]},
    }},
    {name:"Orientalid",
     description:"Gracile long-headed phenotypic cluster of SW Asian and N African desert/steppe belt — Arabian Peninsula, Fertile Crescent, Levant, Persia, N Africa (Libyid sub-variant). Adapted to arid hot environments: lean frame, long narrow leptorrhine/aquiline nose (warming dry air), slightly darker skin than Mediterranid, wavy-to-curly dark hair. High body hair similar to Mediterranid. Arabid sub-variant: low flat skull, dolichocephalic. Iranid sub-variant: taller, higher vault. Lactase persistence moderate (~30–50%) — pastoralist heritage with less intense selection than N European cattle herders. Pre-1500 CE.",
     traits:{
      skin_colour:      {binModes:[0,1,2,2,1],peaks:[{mu:2.3, sigma:0.7, amp:2.8}]},
      hair_colour:      {binModes:[0,0,1,2],  peaks:[{mu:2.85,sigma:0.5, amp:3.2}]},
      hair_texture:     {binModes:[0,1,2,2,1,0,0],peaks:[{mu:2.8,sigma:0.8,amp:2.5}]},
      body_hair:        {binModes:[0,0,1,2,2],peaks:[{mu:3.4, sigma:0.65,amp:3.0}]},
      height:           {binModes:[1,1,2,2,1],peaks:[{mu:2.3, sigma:0.8, amp:2.0}]},
      trunk_length:     {binModes:[1,2,2,1,0],peaks:[{mu:2.0, sigma:0.7, amp:2.0}]},
      body_type:        {binModes:[1,2,2,1,0],peaks:[{mu:1.3, sigma:0.75,amp:2.5}]},
      steatopygia:      {binModes:[2,1,0,0,0],peaks:[{mu:0.05,sigma:0.28,amp:5.0}]},
      cephalic_index:   {binModes:[1,2,2,1,0],peaks:[{mu:1.5, sigma:0.8, amp:2.2}]},
      head_height:      {binModes:[2,2,1],    peaks:[{mu:0.6, sigma:0.5, amp:3.0}]},
      head_size:        {binModes:[1,2,1],    peaks:[{mu:1.0, sigma:0.55,amp:2.2}]},
      nose_breadth:     {binModes:[2,2,1,0],  peaks:[{mu:0.4, sigma:0.52,amp:3.5}]},
      face_breadth:     {binModes:[0,1,2,2,1],peaks:[{mu:2.4, sigma:0.8, amp:2.0}]},
      prognathism:      {binModes:[1,2,2,0],  peaks:[{mu:0.85,sigma:0.6, amp:2.8}]},
      eye_folds:        {binModes:[2,2,1,0],  peaks:[{mu:0.35,sigma:0.5, amp:3.5}]},
      male_neoteny:     {binModes:[1,2,2,1],  peaks:[{mu:1.2, sigma:0.75,amp:2.0}]},
      female_neoteny:   {binModes:[0,1,2,2],  peaks:[{mu:1.9, sigma:0.75,amp:2.0}]},
      lactose_tolerance:{binModes:[1,1,2,2,1],peaks:[{mu:2.3, sigma:0.9, amp:2.0}]},
      height_dimorphism:{binModes:[1,2,1,0],  peaks:[{mu:1.3, sigma:0.6, amp:2.8}]},
      muscle_dimorphism:{binModes:[0,1,2,1],  peaks:[{mu:1.9, sigma:0.7, amp:2.2}]},
    }},
  ],
};

